name: Test Action

on:
  workflow_dispatch:
    inputs:
      status:
        description: "Status to test"
        required: true
        default: "success"
        type: choice
        options:
          - success
          - failure
          - cancelled

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Run Slack Notification Action
        uses: ./
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          status: ${{ inputs.status }}
